-- phpMyAdmin SQL Dump
-- version 4.6.5.1
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:8889
-- Tiempo de generación: 28-03-2017 a las 16:36:57
-- Versión del servidor: 5.6.34
-- Versión de PHP: 7.1.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `coches`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `circuitos`
--

CREATE TABLE `circuitos` (
  `cir_id` int(255) NOT NULL,
  `cir_gp_nombre` varchar(400) NOT NULL,
  `cir_nombre` varchar(400) NOT NULL,
  `cir_ciudad` varchar(400) NOT NULL,
  `cir_pais` varchar(400) NOT NULL,
  `cir_fecha` year(4) NOT NULL,
  `cir_vuelta` int(255) NOT NULL,
  `cir_longitud_vuelta` float NOT NULL,
  `cir_ganador` varchar(255) NOT NULL,
  `cir_17` varchar(400) NOT NULL,
  `cir_172` varchar(400) NOT NULL,
  `cir_p1` varchar(400) NOT NULL,
  `cir_p2` varchar(400) NOT NULL,
  `cir_p3` varchar(400) NOT NULL,
  `cir_quality` varchar(400) NOT NULL,
  `cir_race` varchar(400) NOT NULL,
  `cir_foto` varchar(400) NOT NULL,
  `cir_longitud_total` float NOT NULL,
  `cir_record` tinytext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `circuitos`
--

INSERT INTO `circuitos` (`cir_id`, `cir_gp_nombre`, `cir_nombre`, `cir_ciudad`, `cir_pais`, `cir_fecha`, `cir_vuelta`, `cir_longitud_vuelta`, `cir_ganador`, `cir_17`, `cir_172`, `cir_p1`, `cir_p2`, `cir_p3`, `cir_quality`, `cir_race`, `cir_foto`, `cir_longitud_total`, `cir_record`) VALUES
(1, 'Rolex Australian GP', 'Melbourne GP Circuit', 'Melbourne', 'Australia', 1996, 58, 5.303, 'Nico Rosberg', 'Viernes 24 - Domingo 26 Marzo 2017', '26 de Marzo', 'Viernes 12:00 - 13:30', 'Viernes 16:00 - 17:30', 'Sábado 14:00 - 15:00', 'Sábado 17:00 - 18:00', 'Domingo 16:00 - 18:00', 'australia', 307.574, '1:24.125'),
(2, 'Heineken Chinese GP', 'Shanghai Int Circuit', 'Shangai', 'China', 2004, 56, 5.451, 'Nico Rosberg', 'Viernes 07 - Domingo 09 Abril 2017', '09 de Abril', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 12:00 - 13:00', 'Sábado 15:00 - 16:00', 'Domingo 14:00 - 16:00', 'china', 305.066, '1:32.238'),
(3, 'Gulf Air Bahrain GP', 'Bahrain Int Circuit', 'Sakhir', 'Baréin', 2004, 57, 5.412, 'Nico Rosberg', 'Viernes 14 - Domingo 16 Abril 2017', '16 de Abril', 'Viernes 14:00 - 15:30', 'Viernes 18:00 - 19:30', 'Sábado 15:00 - 16:00', 'Sábado 18:00 - 19:00', 'Domingo 18:00 - 20:00', 'barein', 308.238, '1:31.447'),
(4, 'VTB Russian GP', 'Sochi Autodrom', 'Sochi', 'Rusia', 2014, 53, 5.848, 'Nico Rosberg', 'Viernes 28 - Domingo 30 Abril 2017', '30 de Abril', 'Viernes 11:00 - 12:30', 'Viernes 15:00 - 16:30', 'Sábado 12:00 - 13:00', 'Sábado 15:00 - 16:00', 'Domingo 15:00 - 17:00', 'rusia', 309.745, '1:39.094'),
(5, 'GP de España Pirelli', 'Circuit de Bcn-Catalunya', 'Montmeló', 'España', 1991, 66, 4.655, 'Max Verstappen', 'Viernes 12 - Domingo 14 Mayo 2017', '14 de Mayo', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'espana', 307.104, '1:21.670'),
(6, 'GP de Mónaco', 'Circuit de Mónaco', 'Monte Carlo', 'Mónaco', 1950, 78, 3.337, 'Lewis Hamilton', 'Jueves 25 - Domingo 28 Mayo 2017', '28 de Mayo', 'Jueves 10:00 - 11:30', 'Jueves 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'monaco', 260.286, '1:17.939'),
(7, 'GP de Canadá', 'Circuit Gilles-Villeneuve', 'Montréal', 'Canadá', 1978, 70, 4.361, 'Lewis Hamilton', 'Viernes 09 - Domingo 11 Junio 2017', '11 de Junio', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 10:00 - 11:00', 'Sábado 13:00 - 14:00', 'Domingo 14:00 - 16:00', 'canada', 305.27, '1:13.622'),
(8, 'Azerbaijan GP', 'Baku City Circuit', 'Baku', 'Azerbaiyán', 2016, 51, 6.003, 'Nico Rosberg', 'Viernes 23 - Domingo 25 Junio 2017', '25 de Junio', 'Viernes 13:00 - 14:30', 'Viernes 17:00 - 18:30', 'Sábado 14:00 - 15:00', 'Sábado 17:00 - 18:00', 'Domingo 17:00 - 19:00', 'azerbaiyan', 306.049, '1:46.485'),
(9, 'Grosser Preis Von Österreich', 'Red Bull Ring', 'Spielberg', 'Austria', 1970, 71, 4.326, 'Lewis Hamilton', 'Viernes 07 - Domingo 09 Julio 2017', '09 de Julio', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'austria', 307.02, '1:08.337'),
(10, 'Rolex British GP', 'Silverstone Circuit', 'Silverstone', 'Reino Unido', 1950, 52, 5.891, 'Lewis Hamilton', 'Viernes 14 - Domingo 16 Julio 2017', '16 de Julio', 'Viernes 09:00 - 10:30', 'Viernes 13:00 - 14:30', 'Sábado 10:00 - 11:00', 'Sábado 13:00 - 14:00', 'Domingo 13:00 - 15:00', 'uk', 306.198, '1:33.401'),
(11, 'Pirelli Magyar Nagydíj', 'Hungaroring', 'Budapest', 'Hungría', 1986, 70, 4.381, 'Lewis Hamilton', 'Viernes 28 - Domingo 30 Julio 2017', '30 de Julio', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'hungria', 306.63, '1:19.071'),
(12, 'Pirelli Belgian GP', 'Circuit de Spa-Francorchamps', 'Spa-Francorchamps', 'Bélgica', 1950, 44, 7.004, 'Nico Rosberg', 'Viernes 25 - Domingo 27 Agosto 2017', '27 de Agosto', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'belgica', 308.052, '1:47.263'),
(13, 'GP Heineken D\'Italia', 'Autodromo Nazionale Monza', 'Monza', 'Italia', 1950, 53, 5.793, 'Nico Rosberg', 'Viernes 01 - Domingo 03 Septiembre 2017', '03 de Septiembre', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'italia', 306.72, '1:21.046'),
(14, 'Singapore Airlines Singapore GP', 'Marina Bay Street Circuit', 'Marina Bay', 'Singapur', 2008, 61, 5.065, 'Nico Rosberg', 'Viernes 15 - Domingo 17 Septiembre 2017', '17 de Septiembre', 'Viernes 18:00 - 19:30', 'Viernes 21:30 - 23:00', 'Sábado 18:00 - 19:00', 'Sábado 21:00 - 22:00', 'Domingo 20:00 - 22:00', 'singapur', 308.828, '1:47.187'),
(15, 'Petronas Malaysia GP', 'Sepang Int Circuit', 'Sepang', 'Malasia', 1999, 56, 5.543, 'Daniel Ricciardo', 'Viernes 29 - Domingo 01 Octubre 2017', '01 de Octubre', 'Viernes 11:00 - 12:30', 'Viernes 15:00 - 16:30', 'Sábado 14:00 - 15:00', 'Sábado 17:00 - 18:00', 'Domingo 15:00 - 17:00', 'malasia', 310.408, '1:34.223'),
(16, 'Japanese GP', 'Suzuka Int Racing Course', 'Suzuka', 'Japón', 1987, 53, 5.807, 'Nico Rosberg', 'Viernes 06 - Domingo 08 Octubre 2017', '08 de Octubre', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 12:00 - 13:00', 'Sábado 15:00 - 16:00', 'Domingo 14:00 - 16:00', 'japon', 307.471, '1:31.540'),
(17, 'United States GP', 'Circuit of the Americas', 'Austin', 'USA', 2012, 56, 5.513, 'Lewis Hamilton', 'Viernes 20 - Domingo 22 Octubre 2017', '22 de Octubre', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'usa', 308.405, '1:39.347'),
(18, 'GP de México', 'Autódromo Hnos Rodríguez', 'D.F.', 'México', 1963, 71, 4.304, 'Lewis Hamilton', 'Viernes 27 - Domingo 29 Octubre 2017', '29 de Octubre', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 10:00 - 11:00', 'Sábado 13:00 - 14:00', 'Domingo 13:00 - 15:00', 'mexico', 305.354, '1:20.521'),
(19, 'GP do Brasil', 'Autódromo José Carlos Pace', 'Sao Paulo', 'Brasil', 1973, 71, 4.309, 'Lewis Hamilton', 'Viernes 10 - Domingo 12 Noviembre 2017', '12 de Noviembre', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'brasil', 305.909, '1:11.473'),
(20, 'Etihad Airways Abu Dhabi GP', 'Yas Marina Circuit', 'Yas Marina', 'Abu Dhabi', 2009, 55, 5.554, 'Lewis Hamilton', 'Viernes 24 - Domingo 26 Noviembre 2017', '26 de Noviembre', 'Viernes 10:00 - 11:30', 'Viernes 14:00 - 15:30', 'Sábado 11:00 - 12:00', 'Sábado 14:00 - 15:00', 'Domingo 14:00 - 16:00', 'abu', 305.355, '1:40.279');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `escuderias`
--

CREATE TABLE `escuderias` (
  `es_id` int(255) NOT NULL,
  `es_nombre` varchar(400) NOT NULL,
  `es_ano` year(4) NOT NULL,
  `es_sede` varchar(400) NOT NULL,
  `es_coche` varchar(400) NOT NULL,
  `es_titulo` int(255) NOT NULL,
  `es_podium` int(255) NOT NULL,
  `es_pole` int(255) NOT NULL,
  `es_rapido` int(255) NOT NULL,
  `es_descripcion` mediumtext NOT NULL,
  `es_nombre_foto` varchar(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `escuderias`
--

INSERT INTO `escuderias` (`es_id`, `es_nombre`, `es_ano`, `es_sede`, `es_coche`, `es_titulo`, `es_podium`, `es_pole`, `es_rapido`, `es_descripcion`, `es_nombre_foto`) VALUES
(1, 'Mercedes', 1970, 'Brackley, UK', 'F1 W08 EQ Power+', 3, 71, 65, 38, 'Mercedes AMG Petronas Formula One Team1 (nombre comercial de Mercedes-Benz Grand Prix Limited), anteriormente conocida como Mercedes GP Petronas F1 Team es una escudería de Fórmula 1 dirigida por la empresa automovilística alemana Daimler AG, a través de su marca Mercedes-Benz. Se formó en los años 30 y participó en la Fórmula 1 en 1954 y 1955.</p><p>El día 16 de noviembre de 2009, con el anuncio de la compra del equipo campeón de la temporada 2009 Brawn GP, anunció su vuelta a la Fórmula 1 por parte de Mercedes a partir de 2010. Con esta adquisición, McLaren (hasta ahora \"pareja\" de la marca de la estrella en la Fórmula 1) es simplemente un equipo que recibe los motores alemanes, igualmente Mercedes-Benz venderá el 40% de las acciones que posee sobre McLaren, que serán compradas por el equipo de Woking. Estaba previsto que, para 2011, Mercedes se desvincule totalmente de McLaren en lo que respecta a la propiedad del equipo pero esto no ocurrió hasta el 2014, siendo este el último año de McLaren con un motor Mercedes.</p><p>El chasis y motor son construidos por Mercedes. Daimler AG es la empresa propietaria de la escudería.7 El equipo contó en sus filas con Nico Rosberg y al 7 veces campeón del mundo Michael Schumacher, lo que marcó el retorno a la categoría del múltiple campeón desde su retiro en 2006. Su director es Toto Wolff, reemplazando a Ross Brawn (2010-2013). A partir de 2013, el volante de Michael Schumacher pasó a las manos de Lewis Hamilton, quien en la temporada 2014 y 2015 se proclamó campeón del mundo.', 'mercedes'),
(2, 'Red Bull', 1997, 'Milton Keynes, UK', 'RB13', 4, 99, 58, 52, 'Red Bull Racing es una escudería de Fórmula 1 austriaca con base en Milton Keynes (Inglaterra) propiedad de la empresa de bebidas energéticas Red Bull. La compañía adquirió la escudería Jaguar Racing por cerca de 110 millones de dólares cuando la propietaria anterior de este equipo, Ford Motor Company, anunció su retirada de la máxima categoría del automovilismo. La empresa Red Bull posee un equipo filial de Fórmula 1, Scuderia Toro Rosso (\"Red Bull\" traducido al italiano), con sede en Faenza (Italia), desde el que los jóvenes pilotos dan posteriormente el salto al primer equipo.', 'redbull'),
(3, 'Ferrari', 1950, 'Maranello, Italy', 'SF70H', 16, 531, 201, 236, 'Scuderia Ferrari es la división deportiva (Gestione Sportiva) de automóviles Ferrari encargada de las competencias de Fórmula 1. Ferrari Corse Clienti se encarga desde hace poco de casi todas las otras actividades deportivas de la compañía y la atención a equipos privados.</p><p>La primera participación de Ferrari en la Fórmula 1 fue en el Gran Premio de Mónaco de 1950, con el Tipo 125 F1. Es el equipo activo más antiguo del campeonato, y es el que ha conseguido más victorias (221), campeonatos de pilotos (15) y campeonatos de constructores (16). Ha contado con muchos de los mejores pilotos de la Historia de la Fórmula 1 como Michael Schumacher, Niki Lauda, Juan Manuel Fangio, Gilles Villeneuve o Fernando Alonso, entre otros. Los pilotos actuales son Sebastian Vettel y Kimi Räikkönen, y los pilotos de pruebas son Marc Gené, Davide Rigon, Jean-Éric Vergne, Esteban Gutiérrez y Antonio Giovinazzi. El director del equipo es Maurizio Arrivabene.', 'ferrari'),
(4, 'Force India', 1991, 'Silverstone, UK', 'VJM10', 0, 5, 1, 4, 'Sahara Force India Formula One Team, también conocida como Force India, es una escudería india de Fórmula 1 creada en octubre de 2007, surgida a raíz de la compra de Spyker F1 por parte del consorcio formado por el empresario de la India Vijay Mallya y por el holandés Michiel Mol, pagando 88 millones de euros para adquirir la mitad de las acciones del equipo. Participó en el Mundial de Fórmula 1 desde 2008. En octubre de 2011, la compañía India Sahara India Pariwar adquirió el 42,5% de las acciones de Force India F1 por 100 millones de $.</p><p>Sahara Force India F1 Team representa el incremento de participación de India en la Fórmula 1 junto con el Circuito Internacional de Buddh, que albergó el primer Gran Premio de la India en 2011, los pilotos Karun Chandhok y Narain Karthikeyan, y el Sahara India Pariwar Group.', 'force'),
(5, 'Williams', 1978, 'Grove, UK', 'FW40', 9, 241, 128, 133, 'Williams Martini Racing,1 anteriormente conocida como Williams F1 Team y tradicionalmente como Williams Grand Prix Engineering, es un equipo de Fórmula 1 creado en 1977 por Frank Williams y Patrick Head, al asociarse con Walter Wolf Racing. Todos los autos de Williams son llamados \"FW-número\", por las iniciales del fundador del equipo, Frank Williams.</p><p>Williams es considerado uno de los cuatro grandes equipos de la Fórmula 1, junto con Ferrari, McLaren y Mercedes Benz. La primera carrera de la escudería fue en el Gran Premio de España de 1977, cuando el equipo corrió con un chasis March y Patrick Nève como piloto. Williams comenzó a construir sus propios autos el año siguiente. El suizo Clay Regazzoni ganó la primera carrera para el equipo en el Gran Premio de Gran Bretaña de 1979, mientras que en el Gran Premio de Gran Bretaña de 1997, el canadiense Jacques Villeneuve ganó la carrera número 100 para el equipo. De esta manera, Williams se convirtió en uno de los únicos tres equipos en Fórmula 1, junto con Ferrari y el también inglés McLaren, en ganar 100 carreras.</p><p>Siete pilotos han sido campeones del mundo con Williams: Alan Jones, Keke Rosberg, Nelson Piquet, Nigel Mansell, Alain Prost, Damon Hill y Jacques Villeneuve. A su vez, el equipo ganó 9 títulos de contructores entre 1980 y 1997. Este fue un récord hasta que Ferrari lo superó en el año 2000.</p><p>Williams ha trabajado con muchos constructores de motores, pero más satisfactoriamente con Renault: Williams ganó 5 de sus 9 campeonatos de constructores con la casa francesa. Junto con Ferrari, McLaren y Renault (anteriormente Benetton), Williams es una de las cuatro estructuras que han ganado en todos los campeonatos de constructores desde 1979 a 2008 y en todos los campeonatos de pilotos desde 1984 a 2008.', 'williams'),
(6, 'McLaren', 1966, 'Woking, UK', 'MCL32', 8, 391, 155, 154, 'McLaren Racing Limited, conocida comercialmente como McLaren Honda F1 Team,1 es una escudería británica con sede en Woking (Surrey, Inglaterra), fundada en 1963 por Bruce McLaren (1937-1970). Es una de las escuderías más exitosas en la historia de la Fórmula 1, donde obtuvo 8 títulos mundiales de constructores (tercera en el historial), 12 títulos mundiales de pilotos (segunda), 182 victorias (segunda) y 483 podios (segunda).</p><p>Entre los pilotos más destacados en la historia de McLaren se encuentran Emerson Fittipaldi, James Hunt, Denny Hulme, Johnny Rutherford, Niki Lauda, Alain Prost, Ayrton Senna, Mika Häkkinen, David Coulthard, Kimi Raikkonen, Pedro Martínez de la Rosa, Juan Pablo Montoya, Jenson Button, Lewis Hamilton y Fernando Alonso.', 'mclaren'),
(7, 'Toro Rosso', 1985, 'Faenza, Italy', 'STR12', 0, 1, 1, 1, 'La Scuderia Toro Rosso (STR) es una escudería de Fórmula 1 creada a finales de 2005, después de la compra de la escudería Minardi por parte de Red Bull. Actúa como equipo filial del equipo Red Bull Racing, formando jóvenes promesas para dar el salto a la escudería \"madre\". Sólo Sébastien Bourdais compitió con Toro Rosso sin formar parte del programa de jóvenes pilotos de Red Bull. En palabras de su jefe de equipo Franz Tost, Toro Rosso es la expresión de \"juventud, energía, dinamismo y agresividad\", lo que abarca el llevar a nuevos pilotos a la F1. Su sede radica en Faenza, Italia; pero trabajan con un túnel de viento situado en Bicester, Inglaterra.', 'toro'),
(8, 'Haas', 2016, 'Kannapolis, US', 'VF-17', 0, 0, 0, 0, 'Haas F1 Team, anteriormente conocido bajo el nombre de Haas Racing Developments (o Haas Fórmula LLC) es un equipo de carreras de Fórmula 1 construido por el copropietario del equipo Stewart-Haas Racing de la serie NASCAR Sprint Cup Series Gene Haas y que fue fundado y aprobado su entrada por la comisión de la FIA y Bernie Ecclestone en el mes de abril de 2014. El equipo debutara en el inicio de la temporada 2016. Haas Racing Developments tiene su sede en Kannapolis, Carolina del Norte, junto a las instalaciones del equipo filial de la Copa Sprint de NASCAR, el Stewart-Haas Racing, pero los dos equipos serán tratados como entidades distintas.</p><p>Este equipo es el primer constructor norteamericano que entra en la F1 desde el fallido proyecto del USF1 de 2010 , y el primer equipo estadounidense que compite tras el fin de la relación Haas Lola (temporadas 1985 y 1986). Con anterioridad, en la década los años 70, compitieron en la F1 Shadow Racing Cars y Penske Racing.', 'haas'),
(9, 'Renault', 1986, 'Enstone, UK', 'R.S.17', 2, 52, 20, 13, 'Renault Sport F1 Team es una escudería francesa de Fórmula 1, creada en 1977 y que retornó a la categoría para disputar la temporada 2016. Renault no participó como equipo entre 1986-2001 y 2012-2015, limitándose a suministrar motores a otros constructores. Anteriormente compitió en la Fórmula 1 como Equipe Renault Elf y con licencia francesa desde finales de los años 1970 hasta 1985, y regresó con el tradicional nombre de Renault F1 Team a partir de 2002, tras adquirir a Benetton, que a su vez compró el equipo Toleman en 1986. A su vez, en 2011 participó con licencia británica y bajo el nombre comercial de Lotus Renault GP.</p><p>Renault vendió el 75% del equipo a Genii Capital a finales de 2010; renombrando la escudería como Lotus Renault GP y anunciando la creación de Renault Sport F1 para el suministro de motores y tecnología a partir de 2011, el cual sigue controlando el 25% de la escudería. Luego de competir en 2011 como Renault, Genii Capital solicitó el cambio de nombre del equipo en la lista de inscriptos de 2012, luego de que Proton (actual propietaria de la marca Lotus Cars) tomara en 2012 el control del equipo, renombrándolo a Lotus F1 Team y dejando a Renault como proveedor de motores.</p><p>Renault consiguió dos títulos de campeón de pilotos (con Fernando Alonso) y dos títulos como campeón de constructores, ambos en 2005 y 2006.', 'renault'),
(10, 'Sauber', 1993, 'Hinwill, Switzerland', 'C36', 0, 26, 1, 5, 'Sauber F1 Team (anteriormente denominada Sauber Petronas y Sauber Motorsport) es una escudería de Fórmula 1 con base en Hinwil, Suiza. Su nombre se debe al dueño y ex director de la escudería, Peter Sauber. La primera temporada en la que el equipo compitió en la categoría fue la de 1993, y en 2005 fue vendido a BMW, que se lo devolvió a Peter Sauber al acabar la temporada 2009, quien finalmente lo vendió a Longbow Finace, S.A., a la mitad de la temporada del 2016 después de muchas especulaciones sobre la situación financiera del equipo.</p><p>Antes de su ingreso a la Fórmula 1, Sauber participó en otras categorías, como por ejemplo en los campeonatos suizo e internacional y en el Campeonato Mundial de Resistencia, donde consiguió una gran victoria en las 24 horas de Le Mans de 1989 y el título mundial en esa temporada (1989) y en la siguiente (1990).', 'sauber');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `noticias`
--

CREATE TABLE `noticias` (
  `n_id` int(11) NOT NULL,
  `n_noticia` mediumtext NOT NULL,
  `n_titular` varchar(500) NOT NULL,
  `n_entradilla` varchar(10000) NOT NULL,
  `n_hora` date NOT NULL,
  `n_foto` varchar(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `noticias`
--

INSERT INTO `noticias` (`n_id`, `n_noticia`, `n_titular`, `n_entradilla`, `n_hora`, `n_foto`) VALUES
(2, 'Del que más mejora al que menos con respecto a 2016, analizamos el estado de los equipos tras los test de Barcelona.</p><p><strong>Ferrari.</strong> El equipo que más mejora respecto a los mismos test de 2016 (4,1 segundos), acaba con el segundo mejor tiempo y muy buenas sensaciones. Parece solo un paso por detrás de Mercedes. ¿Será de verdad este año el de los italianos?</p><p><strong>Red Bull.</strong> Sorprende por su diseño, tiene un gran chasis y una aereodinámica excepcional.. pero el motor Renault aún no está al nivel. No suelen mostrar su verdadero potencial en los test.</p><p><strong>Renault.</strong> El equipo oficial francés viene de muy atrás y es el tercero que más mejora. Ocupan el puesto de McLaren a final del año pasado y lucharán con Toro Rosso o Force India al principio.</p><p><strong>Williams.</strong> El motor Mercedes es un regalo para este equipo, mejoran mucho y son los terceros más rápidos. Solo la bisoñez de Stroll les ha impedido rodar más. Massa vive en otra juventud.</p><p><strong>Mercedes.</strong> Ya en los primeros test hicieron simulación de carrera. No son tan dominadores, pero siguen un paso por delante del resto pese a las palabras de Hamilton o Lauda. Segundo mejor tiempo, pero han rodado más que nadie, 5.000 kilómetros.</p><p><strong>Haas.</strong> Con un coche muy parecido al Ferrari cada vez son más banco de pruebas de los italianos. Tiempos discretos, más de tres mil kilómetros completados... su objetivo es afianzarse en la zona media.</p><p><strong>Toro Rosso.</strong> Este año tiene dos pilotos, sobre todo Sainz, en plenitud desde el inicio, pero no tanto el motor Renault, aún falto de fiabilidad. Su problema es la falta de evolución durante el año, cuando tengan un motor más potente otros equipos les superarán en otras mejoras. Quinto tiempo más rápido de los test, pero el segundo peor equipo en cuanto a kilómetros. La aerodinámica de James Key debe ser vital al principio de la temporada.</p><p><strong>Sauber.</strong> Según los datos de la pretemporada son el equipo más lento y con menos recursos de la categoría, aunque mejoran más que otros y su balance en vueltas al Circuit es bueno. Estarán atrás si nada cambia.</p><p><strong>Force india.</strong> No lo van a tener fácil Checo y Ocon, pero llevar el motor Mercedes facilita las cosas a los indios. Séptimo mejor tiempo y quinto que más kilómetros ha recorrido.</p><p><strong>McLaren.</strong> Desastre en los test, el equipo que menos mejora, el que menos ha rodado y solo por delante de Sauber en tiempos, aunque a 2,7 segundos del Ferrari. Solo un milagro puede hacer que acaben las carrera de Australia.', 'Análisis: Mercedes sigue delante y McLaren aún más atrás', 'A pesar de que Ferrari es el equipo que más mejora en tiempos con respecto a 2016, los alemanes han hecho todo lo necesario para llegar a Australia primeros.', '2017-03-12', 'news6'),
(3, 'Cuando quedan 15 días para que el semáforo de Melbourne se apague por completo y dé comienzo la temporada de Fórmula 1 2017, es momento de analizar qué piloto llega más preparado a la cita de Australia.</p><p>En este sentido, Valtteri Bottas es el piloto que más tiempo ha estado rodando a los mandos de un monoplaza en el Circuit Barcelona Catalunya. 628 vueltas ha completado el piloto finés de Mercedes con el W08, para un total de 2.923,34 kilómetros y un crono de 1:19.310.</p><p>En segunda posición se encuentra Sebastian Vettel. El piloto de Ferrari se ha mostrado durante toda la pretemporada muy rápido y el coche de Maranello ha sido un habitual de las primeras pociones. El alemán, que ha dado 591 giros a Montmeló, ha contribuido al desarrollo del SF70H con 2.751,11 kilómetros.</p><p>Cerrando este podio ficticio se sitúa el actual subcampeón del mundo. Sin tanta necesidad de conocer las características del coche como su compañero Bottas, Lewis Hamilton ha terminado con 468 vueltas al trazado catalán, logrando un mejor tiempo tres décimas peor que su compañero (1:19.652).</p><p>Si buscamos a los pilotos españoles, los problemas de fiabilidad han lastrado el tiempo en pista de Carlos Sainz y Fernando Alonso. Alarmante es la situación del piloto de McLaren Honda, ya que Alonso es el piloto que llegará con menos preparación de los que competirán en Melbourne.</p><p>190 giros solamente ha podido hacer el piloto asturiano con el McL32. Un registro que no permite a Alonso alcanzar los 1.000 kilómetros (884.45). Una situación que mejora ligeramente si miramos a Stoffel Vandoorne, que con 235 vueltas al Circuit Barcelona Catalunya supera esta cifra por 93 kilometros (1.093,93)</p><p>En cuanto a Sainz, el madrileño ha superado las 300 vueltas a Montmeló con el Toro Rosso. 1.433,74 kilómetros ha dado el STR12 con Carlos Sainz a bordo para un mejor tiempo de 1:19.837, superando en casi cinco décimas, 31 giros y 144.3 kilómetros las estadísticas cosechadas por Daniil Kyvat.', 'Alonso con su McLaren Honda, el piloto que menos rueda', 'Valtteri Bottas fue quien más vueltas completó al Circut Barcelona Catalunya con un total de 628. Fernando, 190.', '2017-03-13', 'news7'),
(4, 'Las modificaciones en el reglamento del Mundial de F-1 han dado buenos resultados en los test de pretemporada. La rebaja es los tiempos es abrumadora y los pilotos están satisfechos con el esfuerzo de Pirelli, el suministrador único. Uno de los más gráficos es Fernando Alonso. El asturiano de McLaren Honda está contento, pese a que su monoplaza no va como les gustaría: \"Ha sido una agradable sorpresa ver cómo podemos atacar las curvas, cómo se siente el agarre. Ahora puedes conducir como quieras y no como niños pequeños para no sobrecalentar los neumáticos. Esta es la mejor forma de sentir un coche de F-1\". Y apostilla para el que quiera entender: \"Ha sido divertido poder conducir libre de nuevo. Ahora solo nos queda a nosotros ser más rápidos que otros rivales en las rectas\".</p><p>De la misma opinión que el bicampeón asturiano es el Nico Hulknrberg, el alemán de Renault. \"Se puede llegar al límite natural con estos compuestos. Estoy muy a favor de ellos, creo que es una gran noticia, para el deporte y para mí también ya que se acerca mucho más a mi estilo de conducción, que es más natural\", finalizó el expiloto de Force India.', 'Alonso: \"Ahora no hay que pilotar como niños pequeños\"', 'El bicampeón español de McLaren Honda cree que los cambios en los Pirelli son acertados: \"Es la mejor manera de sentir un F1\".', '2017-03-13', 'news8'),
(5, 'Uno de los principales temas de debate en torno a la Fórmula 1 es el poco atractivo que producen entre los aficionados los actuales motores V6 Turbo que equipan los monoplazas de la parrilla.</p><p>Un asunto que según el presidente de la FIA, Jean Todt, es casi imposible volver a las configuraciones de motores de años anteriores porque la sociedad no lo permitiría, pero que el presidente ejecutivo de Liberty Media, Greg Maffei, no ha descartado en su intervención en la conferencia del Deutsche Bank 2017.</p><p>\"Si, hay algunas cosas que hacer en torno a los motores, hay algunas cosas que hacer en torno al sistema de DRS, hay algunas cosas que hacer para intentar equilibrar la cantidad de dinero que reciben los equipos...\", argumentó Maffei cuando fue cuestionado sobre la actual Fórmula 1.</p><p>El dirigente estadounidense explicó más en profundidad que es necesario revisar el reparto económico de la Fórmula 1 para corregir las actuales desigualdades: \"Hay enormes diferencias en la Fórmula 1. Los mejores equipos gastan centenares de millones de dólares, mientras los equipos más pequeños no llegan a los 100 millones. Eso es una locura, pero es un tema difícil de abordar. Hay que tratar de igualar estos aspectos porque de esta manera tendemos carreras más competitivas\".</p><p>Más carreras en suelo europeo es una de las premisas que va a tratar de impulsar Liberty Media para recuperar el atractivo de la Fórmula 1: \"Siempre hay pistas que van entrando y saliendo. Es más negativo cuando algún trazado es una carrera tradicional de Europa, que se encuentra en el corazón de los fans. Ya hemos iniciado un proceso para que regresen algunos circuitos. El origen de la Fórmula 1 está en Francia e Inglaterra\".</p><p>Por último, Greg Maffei también hizo hincapié en que se debe aprender y copiar el éxito de las nuevas carreras que a su juicio, realizan un buen espectáculo en torno al evento: \"Una de las cosas que tenemos que hacer es hacer las carreras más convincentes y emocionantes y más beneficiosas para los promotores. Tomar como referencia los mejores Grandes Premios, como el de Ciudad de México, Singapur, Abu Dhabi... Y llevar esas ceremonias a las pistas tradicionales\".', 'La nueva F-1 no descarta cambiar los motores', 'El presidente y CEO de Liberty Media, Greg Maffei, ha repasado la actualidad de la Fórmula 1 en su intervención en el Deutsche Bank 2017.', '2017-03-12', 'news5'),
(6, 'Una vez finalizada la pretemporada en el Circuit Barcelona - Catalunya, todas las escuderías han regresado a sus fábricas para analizar en profundidad todos los datos recogidos y hacer una simulación de dónde podrían estar en Australia.</p><p>Uno de los aspectos más difíciles de examinar para los equipos es interpretar el mejor registro logrado por cada piloto cuando realizan un simulacro de clasificación de Gran Premio, ya que intervienen tantos parámetros en juego que es muy complicado obtener una imagen clara de la parrilla.</p><p>En AS hemos querido realizar ese estudio cogiendo como referencia el neumático ultrablando, la goma más utilizada por los equipos para esta operación, ya que es la que mayor rendimiento a una vuelta ofrece al monoplaza.</p><p>Tomando como referencia que todos los coches rodarían con la misma cantidad de combustible y los datos ofrecidos por Pirelli, que aseguran que entre el neumático medio y blanco hay una diferencia de 1.5-1.6 segundos, entre el blando y superblando, 0.3.-0.5 segundos y entre superblando y ultrablando, 0.3.-0.5 segundos, Kimi Raikkonen seguiría ostentando el mejor tiempo de las ocho jornadas de test.</p><p>Un registro que se vería rebajado en tres décimas en el peor de los casos y cinco décimas en el mejor hasta llegar al 1:18,134 como máximo, ya que el piloto finés de Ferrari marcó su tiempo con neumáticos superblandos.</p><p>En segundo lugar de esta ficticia clasificación estaría Valtteri Bottas. El piloto finlandés de Mercedes logró su mejor tiempo (1:19,310) en el sexto día con neumáticos superblandos. Aplicando el barómetro de Pirelli, Bottas podría haber conseguido un 1:18,810 en el mejor de los casos.</p><p>Cerrando el podio de pilotos más rápidos de la pretemporada se situaría Max Verstappen con su Red Bull. El piloto holandés hubiese marcado un 1:18:938, mientras que Sebastian Vettel descendería de la segunda posición a la cuarta en esta tabla de tiempos.</p><p>La gran sorpresa sería Lance Stroll, que ascendería desde la decimotercera a la quinta posición. El piloto canadiense debutante esta temporada con Williams, vería mejorado su registro de 1:20,335 del octavo día con gomas blandas hasta un segundo.', 'Raikkonen habría marcado un 1:18.134 con ultrablandos', 'Nuestros compañeros de AS han simulado cómo hubiesen quedado los tiempos en caso de que todos los pilotos hubiesen utilizado el neumático más blando.', '2017-03-12', 'news4'),
(7, 'Honda ya admite que la situación es preocupante. Las dos semanas de test han dejado a McLaren en desventaja con el resto de escuderías, porque los rodajes han sido cortos y de baja calidad y el programa de pruebas previsto apenas ha podido completarse con tantas interrupciones. El responsable del fabricante japonés, Yusuke Hasegawa, reconoce que lo que viene por delante serán semanas duras y el panorama en Australia puede ser parecido.&#34;Hemos mejorado el rendimiento de nuestro motor, aunque parece que la mejora del resto es mayor que la nuestra. Puede que estemos aún más atrás, eso es muy decepcionante. Teniendo en cuenta los reglajes puede que hagamos algo en estas dos semanas para ver cómo afinar el motor y tener mejor rendimiento&#34;, afirma el nipón en Racer.com.Y se explica: &#34;Sabíamos el nivel de rendimiento nuestro, pero no el del resto de los equipos. Así que en comparación estamos un poco asustados por la situación y es demasiado optimista para nosotros esperar un muy buen resultado en Melbourne. Pero viéndolo desde el lado de los problemas, no esperaba la amplia variedad de problemas que hemos sufrido&#34;. Sobre si han encontrado explicaciones a las averías y problemas, admite que no para todas: &#34;Todo lo que ha sucedido no se ha visto en el banco de pruebas, creo que no. Especialmente la avería del segundo día y la del primer día de la segunda semana. No esperábamos un problema así&#34;. &#34;Obviamente es decepcionante pero para mí es bueno encontrar los problemas antes de Melbourne. Aunque lógicamente es malo para las pruebas y por romper el tiempo de rodaje&#34;, finaliza.', 'En Honda están &#34;asustados&#34; y no esperaban tantos problemas', '&#34;Puede que estemos aún más atrás, eso es muy decepcionante&#34;, afirma Hasegawa en Racer tras dos semanas duras de test.', '2017-03-11', 'news3'),
(8, 'Los problemas de fiabilidad han estado presentes durante toda la pretemporada. Un aspecto que Helmut Marko espera que Renault solucione con la actualización prevista para el Gran Premio de España: \"Un sensor de la MGU-K se rompió en varias ocasiones en la primera semana de test. Nos dijeron desde Renault que en la segunda semana se solucionaría el problema, pero volvió a suceder. Al parecer, es una serie defectuosa del proveedor. Esperamos alcanzar a Mercedes y Ferrari en el verano con la actualización del motor para el Gran Premio de España\".</p><p>Marko ha admitido que Daniel Ricciardo y Max Verstappen se han encontrado cómodos en el monoplaza, así como la principal preocupación es que no consiguen hacer funcionar bien los neumáticos: \"A veces conseguimos que los neumáticos funcionen en la ventana de temperatura adecuada, por lo que obtenemos un rendimiento óptimo\".</p><p>El asesor de la escudería de Red Bull ha afirmado que la suspensión del RB13 está dentro del reglamento de cara a una posible reclamación en Australia por parte de algún equipo: \"Es un asunto muy complejo. Uno debe mirar a los componentes individuales. Pero por supuesto, estamos dentro del reglamento. Ahora tenemos que demostrar que todo es compatible. Siempre van a existir zonas grises en un reglamento. La FIA tiene un puñado de técnicos que se enfrentan a un ejército de especialistas en cada equipo\".</p><p>Por último, Marko y Mateschitz expresaron la misma perspectiva acerca de cómo se puede desarrollar la temporada de Fórmula 1 2017: \"Ferrari convence por su estabilidad y por un progreso significativo con respecto al año anterior. Son un serio oponente a la parte superior de la parrilla. Mercedes parece tener problemas con el fondo plano. Su gran superioridad se ha ido. Mientras Bottas debe mostrar que puede conducir al mismo nivel que Hamilton, la Scuderia Ferrari solamente tiene Vettel para los mejores puestos. Por lo tanto, nosotros estamos en las mejores condiciones con Verstappen y Ricciardo para lograr el Mundial de equipos\".', 'Red Bull espera alcanzar a Ferrari y Mercedes en el verano', 'Didi Mateschitz y Helmut Marko han analizado el rendimiento del RB13 en la pretemporada disputada en el Circuit Barcelona - Catalunya.', '2017-03-11', 'news2'),
(9, 'En las tinieblas, a veces, se encuentran momentos brillantes, de esos que no se olvidan jamás. Y Fernando Alonso siempre guardará en el recuerdo que, en uno de sus peores momentos como piloto de Fórmula 1, tuvo que salir a saludar a la multitud que le aclamaba en la tribuna principal de Barcelona en el último día de test de 2017.</p><p>Antes de eso los aficionados abuchearon el regreso del coche al box después de la segunda bandera roja que protagonizó el asturiano con su McLaren. Después de todo Fernando reconocía que es complicado ver el lado bueno de las cosas: “Ha sido una forma decepcionante de terminar los test, ya que no pudimos aprovechar al máximo el último día de carrera. La mañana comenzó de manera positiva y estábamos trabajando bien a través de nuestro programa, hasta que el coche perdió potencia en una curva y se apagó así que tuve que parar”.</p><p>Y siguió con su relato de la jornada: \"Logramos volver a pista de nuevo sin ningún problema, y todo funcionó sin problemas durante unas pocas vueltas hasta que sucedió de nuevo, así que nos dimos cuenta de que necesitábamos investigar más a fondo durante la hora del almuerzo y hacer más cambios”. “Estoy contento de que pudiéramos volver por la tarde, queríamos estar todo el tiempo posible ya que cada vuelta es útil para nuestro aprendizaje”.</p><p>Aún así el español se centra en lo importante, trabajar para llegar a la primera carrera del año en condiciones de terminarla y ser competitivo, algo que en estos momentos parece un milagro: \"Está claro que tenemos mucha preparación por delante para estar listos a tiempo para Melbourne. Sé que el equipo está trabajando duro y podremos encontrar más respuestas una vez que consigamos el coche de vuelta a la fábrica. Tengo la esperanza de que podremos dar el siguiente paso para estar listos en Melbourne”. Veremos.', 'Alonso y el último día de test: “Ha sido decepcionante”', 'El asturiano reconoce que deben trabajar duro para llegar a tiempo a Melbourne: “Tengo esperanza de que estemos listos para Australia”.', '2017-03-10', 'news1');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pilotos`
--

CREATE TABLE `pilotos` (
  `p_id` int(255) NOT NULL,
  `p_nombre` varchar(400) NOT NULL,
  `p_apellido` varchar(400) NOT NULL,
  `p_numero` int(255) NOT NULL,
  `p_nacimiento` date NOT NULL,
  `p_debut` year(4) NOT NULL,
  `p_pais` varchar(255) NOT NULL,
  `p_n_titulo` int(255) NOT NULL,
  `p_n_podium` int(255) NOT NULL,
  `p_n_punto` int(255) NOT NULL,
  `p_n_gp` int(255) NOT NULL,
  `p_minitexto` varchar(10000) NOT NULL,
  `p_descripcion` mediumtext NOT NULL,
  `es_id_fk` int(255) DEFAULT NULL,
  `p_nombre_foto` varchar(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `pilotos`
--

INSERT INTO `pilotos` (`p_id`, `p_nombre`, `p_apellido`, `p_numero`, `p_nacimiento`, `p_debut`, `p_pais`, `p_n_titulo`, `p_n_podium`, `p_n_punto`, `p_n_gp`, `p_minitexto`, `p_descripcion`, `es_id_fk`, `p_nombre_foto`) VALUES
(1, 'Lewis', 'Hamilton', 44, '1985-01-07', 2007, 'Reino Unido', 3, 104, 2247, 188, '     El inglés afronta una nueva temporada con ganas de recuperar el título. Después de verse derrotado por Nico Rosberg, Hamilton tendrá que derrotar a un nuevo compañero, Valtteri Bottas. Con varios récords a su alcance, 2017 puede ser un año muy importante en la carrera del británico.&#34;&#34;&#34;&#34;&#34;', 'Lewis Carl Davidson Hamilton, MBE (Stevenage, Hertfordshire, Inglaterra, Reino Unido, 7 de enero de 1985) es un piloto británico de Fórmula 1. Desde 2007 hasta 2012, fue piloto de la escudería McLaren de Fórmula 1, con la cual fue campeón en 2008 y subcampeón en 2007. A partir de 2013, se convirtió en piloto de Mercedes AMG, quedando campeón en 2014 y 2015, y subcampeón en 2016. Ha logrado 53 victorias a lo largo de su carrera en la Fórmula 1 situándose en la segunda posición total de victorias conseguidas, además de 104 podios y 61 pole.', 1, 'hamilton'),
(2, 'Valtteri', 'Bottas', 77, '1989-08-28', 2013, 'Finlandia', 0, 9, 411, 78, 'El piloto finlandés está ante la mayor oportunidad de su carrera. Tras una buena etapa en Williams, sustituirá a Nico Rosberg con el reto de igualar la hazaña del alemán, superar a Lewis Hamilton y proclamarse campeón del mundo.', 'Valtteri Bottas (28 de agosto de 1989, Nastola, Finlandia) es un piloto de automovilismo finlandés. En la actualidad reside en Mónaco y compite para el equipo Mercedes en sustitución de Nico Rosberg, quien se retiró al final del 2016. Anteriormente compitió en Williams Racing como piloto titular desde 2013, con el que resultó cuarto en el campeonato 2014. En 2015 y 2016 vuelve a ser piloto de Williams Racing acabando 5º y 8º respectivamente.</p><p>En 2017, pasa a formar parte de la escudería Mercedes AMG.', 1, 'bottas'),
(3, 'Daniel', 'Ricciardo', 3, '1989-07-01', 2011, 'Australia', 0, 18, 616, 109, 'Después de superar a Max Verstappen la temporada pasada, el reto para el australiano es el de pelear cara a cara con Mercedes. Red Bull se agarra al cambio de normativa para igualar la batalla con los de Brackley. Esta es la temporada en la que Ricciardo quiere presentar su candidatura al título mundial.', 'Daniel Ricciardo (Perth, Australia, 1 de julio de 1989) es un piloto australiano de automovilismo de velocidad. Ganó la Fórmula 3 Británica en el año 2009. En las temporadas de 2012 y 2013, fue el primer piloto de la escudería Toro Rosso de Fórmula 1. Desde la 2014 es titular en el equipo Red Bull junto a Max Verstappen. Ha logrado cuatro victorias, una pole position y once podios en la Fórmula 1, y quedó tercero en las temporadas 2014 y 2016, solo por detrás de los Mercedes de Hamilton y Rosberg.', 2, 'ricciardo'),
(4, 'Max', 'Verstappen', 33, '1997-09-30', 2015, 'Holanda', 0, 7, 253, 40, 'El piloto holandés encara su primera temporada completa como piloto de Red Bull. Después de lograr la primera victoria de su carrera, Verstappen querrá, primero, ganar la batalla con su compañero y después aspirar a ser el campeón del mundo más joven de la historia.', 'Max Emilian Verstappen (Hasselt, Bélgica, 30 de septiembre de 1997) es un piloto de automovilismo neerlandés que compite para el equipo Red Bull Racing de la Fórmula 1. Es el piloto más joven en liderar una vuelta durante un Gran Premio de Fórmula 1, el ganador más joven de un gran premio (18 años 7 meses y 16 días en el Gran Premio de España 2016) , el piloto más joven en conseguir un podio y el piloto más joven en competir en la historia de esta categoría, ya que hizo su debut con 17 años y 166 días en el Gran Premio de Australia de 2015 para la Scuderia Toro Rosso.2 Es, también, el primer piloto de nacionalidad neerlandesa en subir al primer lugar del podio de la F1.', 2, 'verstappen'),
(5, 'Sebastian', 'Vettel', 5, '1987-07-03', 2007, 'Alemania', 4, 86, 2108, 179, 'Después de una decepcionante temporada, Vettel espera que su tercer año al volante de Ferrari traiga, al menos, los éxitos de 2015. Los de Maranello se vieron superados por Red Bull perdiendo el subcampeonato de constructores. El alemán quiere volver a lo más alto y confía poder hacerlo en Ferrari.', 'Sebastian Vettel (Heppenheim, Hesse, 3 de julio de 1987) es un piloto alemán de automovilismo de velocidad. Ha ganado cuatro títulos mundiales de Fórmula 1 con el equipo Red Bull en 2010, 2011, 2012 y 2013 más un subcampeonato en 2009. Debutó en 2007 con el equipo BMW Sauber y participó en 2008 con el equipo Toro Rosso logrando su primera victoria en el Gran Premio de Italia de 2008.</p><p>Se convirtió el 27 de octubre de 2013 en el piloto más joven de la historia en ser tetracampeón de la máxima categoría de automovilismo. Comenzando la temporada 2016, lleva acumuladas 42 victorias, 80 podios y 46 pole position. Es el cuarto piloto con más grandes premios ganados en la historia. Iguala a Alain Prost (4) en número de títulos mundiales, superado por Juan Manuel Fangio (5) y Michael Schumacher (7).</p><p>Vettel ostentaba el récord como piloto más joven en conseguir una victoria en la Fórmula 1, conseguida en el Gran Premio de Italia de 2008, aunque actualmente lo ha superado Max Verstappen al ganar en el Gran Premio de España de 2016.</p><p>El 26 de marzo de 2014 recibe el Premio Laureus al Mejor Deportista Masculino del Año (2013).', 3, 'vettel'),
(6, 'Kimi', 'Räikkönen', 7, '1979-10-17', 2001, 'Finlandia', 1, 84, 1360, 253, 'El finlandés volvió a ser derrotado por Sebastian Vettel, al igual que ocurrió en la primera campaña del alemán en Ferrari. Raikkonen confía en disponer de un Ferrari competitivo que le permita luchar por algo más que terceros puestos.', 'Kimi-Mattias Räikkönen (Espoo, 17 de octubre de 1979) es un piloto de automovilismo finlandés. Fue campeón mundial de Fórmula 1 en 2007 como piloto de Ferrari y subcampeón en 2003 y 2005 con McLaren.</p><p>Tras la temporada 2009, el piloto cambió de disciplina para competir en el Campeonato Mundial de Rally para Citroën. Allí logró un quinto en el Rally de Turquía de 2010 como mejor resultado. El finlandés terminó en el décimo lugar del campeonato de pilotos de 2010 y 2011. Räikkönen, Carlos Reutemann y Robert Kubica son los únicos pilotos de Fórmula 1 que han conseguido sumar puntos en el Campeonato del Mundo de Rally, siendo Reutemann el único en haber subido al podio y Räikkönen en haberlo logrado siendo campeón del mundo de F1.</p><p>Räikkönen retornó a la Fórmula 1 en 2012 para pilotar para Lotus, quedando tercero en el campeonato mundial de pilotos. El piloto volvió a correr con Ferrari en 2014. En su carrera en la máxima categoría de automovilismo, el finlandés ha obtenido 20 victorias y 84 podios.', 3, 'raikonen'),
(7, 'Sergio', 'Pérez', 11, '1990-01-26', 2011, 'México', 0, 7, 367, 116, 'Volverá a ejercer de jefe de filas en Force India. La temporada pasada, Checo logró dos podios muy importantes para mantener el cuarto puesto en el Mundial de constructores. La escudería india intentará darle un monoplaza capaz de competir, en mayor o menor medida, con Mercedes, Ferrari o Red Bull.', 'Sergio Pérez Mendoza (Guadalajara, Jalisco, México, 26 de enero de 1990) también conocido como Checo Pérez, es un piloto de automovilismo de velocidad mexicano. Está vinculado desde el 2014 al equipo Force India de Fórmula 1. También forma parte de Escudería Telmex.</p><p>Entre sus logros más destacados en su carrera, han sido dos segundos lugares en el Gran Premio de Malasia e Italia en 2012; en la temporada 2010 de GP2 Series, Pérez logró su primera victoria en la categoría en el Principado de Mónaco a la que siguieron otros tres triunfos. El día 4 de octubre de 2010, se confirmó que Pérez ingresa a la Fórmula 1 en la escudería Sauber para la temporada 2011 y posteriormente en la temporada 2012, con el mismo equipo, conquistó 3 podios. En 2013 pilotea con el equipo McLaren y al cierre del mismo año, se anunció como piloto oficial de Sahara Force India F1 Team con quien acumula cuatro podios.</p><p>Por sus logros a corta edad y a sus buenos resultados, en 2012 la alemana prensa lo denominó «The Mexican Wunderkind» (El niño prodigio mexicano).', 4, 'perez'),
(8, 'Esteban', 'Ocon', 31, '1996-09-17', 2016, 'Francia', 0, 0, 0, 9, 'Primer año para el piloto francés en Force India. Después de debutar a mitad de temporada en Manor, se prepara para su primer año completo en Fórmula 1. Los ojos de Mercedes estarán muy pendientes de su rendimiento para ver de qué es capaz con un coche competitivo.', 'Esteban Ocon (Évreux, 17 de septiembre de 1996) es un piloto francés de automovilismo de velocidad que corrió durante la temporada 2016 de Fórmula 1 con el equipo Manor, reemplazando a Rio Haryanto por problemas económicos a partir del GP de Bélgica. Actualmente es piloto oficial de la escudería Force India.', 4, 'ocon'),
(9, 'Felipe', 'Massa', 19, '1981-04-25', 2002, 'Brasil', 0, 41, 1124, 251, 'Después de su intento de retirada, vuelve para llenar el hueco que deja Valtteri Bottas tras su marcha a Mercedes. El brasileño ejercerá de mentor para su jovencísimo compañero, Lance Stroll. Buscará pelear por algún podio en los circuitos favorables para Williams.', 'Felipe Massa (São Paulo, 25 de abril de 1981) es un piloto de automovilismo de velocidad brasileño. Fue piloto de la Scuderia Ferrari de Fórmula 1 desde la temporada 2006 hasta la 2013, y es piloto oficial de Williams desde la temporada 2014. Ha obtenido 11 victorias y 40 podios a lo largo de su carrera. Además, resultó subcampeón en 2008, tercero en 2006, cuarto en 2007 y sexto en 2010, 2011 y 2015.', 5, 'massa'),
(10, 'Lance', 'Stroll', 18, '1998-10-29', 2017, 'Canadá', 0, 0, 0, 0, 'El canadiense es el más joven de la parrilla. Llega desde la F3 con ganas de demostrar que está en Williams por su talento y no por el dinero que trae detrás. Tendrá en Massa un gran espejo en el que mirarse.', 'Lance Stroll (29 de octubre de 1998, Montreal) es un piloto canadiense de automovilismo de velocidad. En la temporada 2017 de Fórmula 1 será piloto titular de Williams Racing.3', 5, 'stroll'),
(11, 'Fernando', 'Alonso', 14, '1981-07-29', 2001, 'España', 2, 97, 1832, 274, 'Tercer año del piloto asturiano en la escudería británica. Tanto él como McLaren buscan dar el salto de calidad definitivo que les permita luchar con los mejores. Deberían estar asentados con facilidad en la zona de puntos y aspirar a la cuarta plaza del campeonato de constructores.', 'Fernando Alonso Díaz (Oviedo, Asturias, España, 29 de julio de 1981) es un piloto español de Fórmula 1. Ha ganado dos veces el Campeonato Mundial de Pilotos de Fórmula 1 en 2005 y 2006, ha sido subcampeón en 2010, 2012 y 2013, y obtuvo un tercer puesto en 2007 empatando con su compañero de equipo Lewis Hamilton. Ha competido para los equipos Minardi, Renault F1 Team (en el que fue bicampeón del mundo), McLaren y Scuderia Ferrari, siendo esta su escudería desde 2010 hasta 2014. El 20 de noviembre de 2014 la Scuderia Ferrari anuncia su marcha después de 5 temporadas. El 11 de diciembre de 2014 se anuncia su regreso a McLaren de la mano de Honda.</p><p>Alonso es el sexto piloto con mayor cantidad de victorias en la historia de la Fórmula 1 con 32 grandes premios ganados y el tercer piloto con más podios: 97. Entre sus triunfos se cuentan 3 en el Gran Premio de Malasia, 3 en el Gran Premio de Alemania, 3 en el Gran Premio de Europa (uno de ellos en España), 2 en el Gran Premio de Mónaco, 2 en el Gran Premio de Gran Bretaña, 2 en el Gran Premio de Italia, 2 en el Gran Premio de Japón, y otros 2 en el Gran Premio de España.</p><p>Junto a Alfonso de Portago y Pedro de la Rosa, Alonso es uno de los tres españoles que han alcanzado el podio en esta competición, siendo el único que ha logrado victorias. Es además uno de los cuatro pilotos que han debutado en Ferrari con victoria en la primera carrera (junto con Mario Andretti, Nigel Mansell y Kimi Räikkönen).', 6, 'alonso'),
(12, 'Stoffel', 'Vandoorne', 2, '1992-03-26', 2016, 'Bélgica', 0, 0, 1, 1, 'Primera temporada completa del belga en la Fórmula 1. Después de esperar pacientemente a la sombra de Alonso y Button, llega su turno. Quiere demostrar que tiene talento para pelear con los mejores y ser la cabeza visible de McLaren para los próximos años.', 'Stoffel Vandoorne (Kortrijk, Bélgica, 26 de marzo de 1992) es un piloto belga de automovilismo de velocidad. Obtuvo el subcampeonato de la Fórmula Renault 3.5 en 2013, y fue campeón de la GP2 Series en 2015 con el equipo ART Grand Prix. En 2013 ingresó al Programa de Jóvenes Pilotos de McLaren, y actualmente es piloto oficial de McLaren tras la retirada de Jenson Button. En el 2016 salió 4° en la Super Fórmula Japonesa, con Honda, y disputó el Gran Premio de Baréin, sustituyendo a Fernando Alonso.', 6, 'vandoorne'),
(13, 'Carlos', 'Sainz', 55, '1994-09-01', 2015, 'España', 0, 0, 64, 40, 'Tercera temporada del español en Toro Rosso. Después de grandes actuaciones la pasada temporada, quiere consolidarse definitivamente en el campeonato. Es un año muy importante para él, acaba contrato y tiene la oportunidad de despertar el interés de los principales equipos de la parrilla.', 'Carlos Sainz Vázquez de Castro (Madrid, 1 de septiembre de 1994), usualmente conocido como Carlos Sainz Jr., es un piloto de automovilismo español, que ha disputado varias competiciones internacionales, como las World Series by Renault con el equipo DAMS, que ganó en 2014. Es piloto de la Scuderia Toro Rosso en la temporada 2016 de Fórmula 1. Es hijo del excampeón mundial de rallies Carlos Sainz.', 7, 'sainz'),
(14, 'Daniil', 'Kvyat', 26, '1994-04-26', 2014, 'Rusia', 0, 2, 128, 59, 'Después de una temporada muy difícil para el ruso, quiere demostrar el talento que le llevó a lograr podios con Red Bull. Su primer objetivo será batir a Carlos Sainz después de verse superado claramente por el español durante la segunda mitad de la pasada campaña.', 'Daniil Viacheslávovich Kvyat (Ufá, Baskortostán, Rusia, 26 de abril de 1994) es un piloto ruso de automovilismo de velocidad. Debutó en la Fórmula 1 como sustituto del piloto Daniel Ricciardo en el equipo italiano Toro Rosso para la temporada 2014, y actualmente es compañero de Carlos Sainz Jr. en Toro Rosso. En el año 2012 fue campeón de la Fórmula Renault 2 con 7 victorias. En 2013 compitió en la Fórmula 3 Europea y se proclamó campeón de la GP3 Series.', 7, 'kvyat'),
(15, 'Romain', 'Grosjean', 8, '1986-04-17', 2009, 'Francia', 0, 10, 316, 104, 'El piloto francés se ganó su continuidad en la escudería estadounidense gracias a sus buenas actuaciones en 2016. Logró los 29 puntos que consiguió Haas, venciendo de una manera muy clara a su compañero Esteban Gutiérrez. Ahora, como claro líder del equipo, tratará de repetir el gran rendimiento de la pasada campaña.', 'Romain Grosjean (Ginebra, Suiza, 17 de abril de 1986) es un piloto de automovilismo de velocidad francés. Fue campeón de la Fórmula 3 Euroseries 2007 y la GP2 Series 2011. Grosjean ha disputado la Fórmula 1 en 2009 para Renault, y a partir de 2012 para Lotus. El piloto ha conseguido diez podios, y finalizó séptimo en el campeonato 2013 y octavo en 2012.', 8, 'grosjean'),
(16, 'Kevin', 'Magnussen', 20, '1992-10-05', 2014, 'Dinamarca', 0, 1, 62, 41, 'Después de un año en Renault llega a Haas para tratar de demostrar el talento que apuntó en su única campaña con McLaren, en la que logró su único podio. Todavía joven, se esperan grandes cosas del danés en la F1.', 'Kevin Magnussen (Roskilde, Dinamarca, 5 de octubre, de 1992) es un piloto danés de automovilismo de velocidad. Es hijo del piloto retirado de Fórmula 1 Jan Magnussen. En 2013 ganó el campeonato de Formula Renault 3.5 Series y fue miembro del Programa de Jóvenes Pilotos de McLaren.1 Debutó en la Fórmula 1 en 2014 con el equipo McLaren con un segundo puesto en su primera carrera. En temporada 2016, vuelve a correr con Renault, en sustitución de Pastor Maldonado. Para la temporada 2017, cambia de equipo y será compañero de Romain Grosjean en la escudería estadounidense Haas F1 Team.', 8, 'magnussen'),
(17, 'Nico', 'Hulkenberg', 27, '1987-08-19', 2010, 'Alemania', 0, 0, 362, 117, 'Llega como fichaje de estrella de la escudería. El piloto alemán tiene ganas de reivindicarse después de que su etapa en Force India no fuera tan exitosa cómo se esperaba. Será la cabeza visible de un proyecto que quiere ser ganador a largo plazo.', 'Nicolas \"Nico\" Hülkenberg (Emmerich am Rhein, Alemania, 19 de agosto de 1987) es un piloto alemán de Fórmula 1 que forma parte del equipo Renault F1 Team como piloto titular para la temporada 2017. Por otra parte, fue ganador absoluto de la prueba de resistencia de las 24 Horas de Le Mans de 2015 en su primera participación.', 9, 'hulkenberg'),
(18, 'Jolyon', 'Palmer', 30, '1991-01-20', 2016, 'Reino Unido', 0, 0, 1, 21, 'Después de un año en Renault llega a Renault para tratar de demostrar el talento que apuntó en su única campaña con McLaren, en la que logró su único podio. Todavía joven, se esperan grandes cosas del danés en la F1.', 'Jolyon Palmer (Horsham, 20 de enero 1991) es un piloto de automovilismo británico, campeón de la GP2 Series 2014. En 2016 dio el salto a la F1, siendo piloto oficial de Renault junto al danés Kevin Magnussen.</p><p>Para 2017, seguirá siendo piloto de Renault, pero esta vez tendrá a Nico Hülkenberg como compañero de equipo.', 9, 'palmer'),
(19, 'Pascal', 'Wehrlein', 94, '1994-10-18', 2016, 'Alemania', 0, 0, 1, 21, 'Después de un invierno convulso en el que llegó a sonar como candidato al volante de Mercedes, el alemán seguirá fogueándose en la en el equipo Sauber. Tratará de demostrar a Mercedes que estaba preparado para ocupar el puesto que fue para Bottas.', 'Pascal Wehrlein (18 de octubre de 1994, Sigmaringen, Baden-Württemberg) es un piloto de automovilismo alemán1. Actualmente es piloto oficial de la escudería suiza Sauber F1 Team.</p><p>El 10 de febrero de 2016, el piloto confirmó que en 2016 competiría en Fórmula 1 con el equipo Manor Racing. Consiguió el primer punto del equipo al terminar 10º en Austria.</p><p>El 16 de enero de 2017, se anuncia su fichaje por el equipo suizo Sauber F1 Team para la temporada 2017 de fórmula 1.', 10, 'wehrlein'),
(20, 'Marcus', 'Ericsson', 9, '1990-09-02', 2014, 'Suecia', 0, 0, 9, 56, 'El sueco disputará su tercera temporada con Sauber tratando de mejorar sus resultados de la pasada campaña, en la que ni siquiera fue capaz de puntuar. Si quiere mostrar que es capaz de ser competitivo en la Fórmula 1, este tiene que ser su año.', 'Marcus Ericsson (Kumla, Suecia, 2 de septiembre de 1990) es un piloto sueco de automovilismo de velocidad, que actualmente corre en la Fórmula 1 para el equipo Sauber.</p><p>El 21 de noviembre de 2013, salió a la luz que Ericsson era un candidato para pilotar en el equipo de Caterham en 2014 con Kamui Kobayashi como compañero de equipo. Dos meses después, el 21 de enero de 2014, el equipo anunció oficialmente que Ericsson y Kobayashi serían sus pilotos titulares para la próxima temporada, con Robin Frijns como piloto reserva. Logró terminar 14º en su segunda carrera en la máxima categoría, y en el GP de Mónaco, se quedó a las puertas de puntuar, consiguiendo su mejor resultado del año (11º). El resto de la temporada fue para olvidar con unos registros pobres al volante del peor coche de la parrilla.</p><p>El 1 de noviembre de 2014, Sauber confirma a Ericsson para 2015.', 10, 'ericsson');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE `usuarios` (
  `u_id` int(255) NOT NULL,
  `u_email` varchar(400) NOT NULL,
  `u_contrasena` varchar(400) NOT NULL,
  `u_permiso` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`u_id`, `u_email`, `u_contrasena`, `u_permiso`) VALUES
(1, 'dani@gmail.com', '$2a$04$ZzyoLNSatEXe.eSidKA2kOGuLJkZE3MbNmfakL22LroeSm2lURnFG', 1),
(2, 'jmanzano2@gmail.com', '$2a$04$3EYbikxu4CJ7OukRs9QATeQJWNaXq6MgxtkvKiRR249DrMWhG6xxi', 1);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `circuitos`
--
ALTER TABLE `circuitos`
  ADD PRIMARY KEY (`cir_id`),
  ADD KEY `p_id_fk` (`cir_ganador`);

--
-- Indices de la tabla `escuderias`
--
ALTER TABLE `escuderias`
  ADD PRIMARY KEY (`es_id`);

--
-- Indices de la tabla `noticias`
--
ALTER TABLE `noticias`
  ADD PRIMARY KEY (`n_id`);

--
-- Indices de la tabla `pilotos`
--
ALTER TABLE `pilotos`
  ADD PRIMARY KEY (`p_id`),
  ADD KEY `equipo` (`es_id_fk`),
  ADD KEY `es_id_fk` (`es_id_fk`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`u_id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `circuitos`
--
ALTER TABLE `circuitos`
  MODIFY `cir_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
--
-- AUTO_INCREMENT de la tabla `escuderias`
--
ALTER TABLE `escuderias`
  MODIFY `es_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
--
-- AUTO_INCREMENT de la tabla `noticias`
--
ALTER TABLE `noticias`
  MODIFY `n_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
--
-- AUTO_INCREMENT de la tabla `pilotos`
--
ALTER TABLE `pilotos`
  MODIFY `p_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
--
-- AUTO_INCREMENT de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `u_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `pilotos`
--
ALTER TABLE `pilotos`
  ADD CONSTRAINT `pilotos_ibfk_1` FOREIGN KEY (`es_id_fk`) REFERENCES `escuderias` (`es_id`) ON DELETE SET NULL ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
